name: "DEV DEPLOY"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: prod
      aws-assume-role-arn: "arn:aws:iam::767397741290:role/github-actions-ErickClinton-pipeline"
      aws-region: "sa-east-1"
      aws-statefile-s3-bucket: "erickclinton-sa-east-1-terraform"
      aws-lock-dynamodb-table: "erickclinton-sa-east-1-terraform"